spring:
  data:
    mongodb:
      uri: mongodb://root:123456@localhost:7017/service_db?authSource=admin
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration


app:
  allowed-origin: "http://localhost:4200"



